name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: pzalejko/spring-boot-native-example-with-github-actions
      DOCKER_IMAGE_TAG: $(echo $GITHUB_RUN_NUMBER)

    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Set up JDK 
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.0'
        java-version: '17'
    - 
      name: Build with Maven
      run: mvn clean -Pnative spring-boot:build-image -Dspring-boot.build-image.imageName=$(echo $DOCKER_IMAGE_NAME):$(echo $DOCKER_IMAGE_TAG) --file demo/pom.xml
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_API_KEY }}
    - 
      name: Docker Push
      run: docker push $(echo $DOCKER_IMAGE_NAME):$(echo $DOCKER_IMAGE_TAG)
