name: CI
on:
  push:
    branches: [ "main", "helm" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: pzalejko/spring-boot-native-example-with-github-actions

    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Set up JDK 
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.0'
        java-version: '17'
    - 
      name: Build with Maven
      run: mvn clean -Pnative spring-boot:build-image -Dspring-boot.build-image.imageName=$(echo $DOCKER_IMAGE_NAME):$(echo $GITHUB_RUN_NUMBER) --file demo/pom.xml
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_API_KEY }}
    - 
      name: Docker Push
      run: docker push $(echo $DOCKER_IMAGE_NAME):$(echo $GITHUB_RUN_NUMBER)

    - name: update helm chart
      run: |
        sed -i 's/tag:.*/tag: '$GITHUB_RUN_NUMBER'/g' spring-boot-native-and-github-actions-helm/values.yaml
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update helm chart (an image version)"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}